services:
  mqtt:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./docker/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./docker/mqtt/data:/mosquitto/data
      - ./docker/mqtt/log:/mosquitto/log
